include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = relaxed
}

queues {
  "wager-transactions-dlq.fifo" {
    fifo = true
    contentBasedDeduplication = false
  }
  "wager-transactions.fifo" {
    fifo = true
    contentBasedDeduplication = false
    deadLettersQueue {
      name = "wager-transactions-dlq.fifo"
      maxReceiveCount = 5
    }
  }
  "wager-events.fifo" {
    fifo = true
    contentBasedDeduplication = false
  }
}
